"""
Advanced modeling utilities for the CSIRO Image2Biomass project.

This module provides reusable functionality for:

- Combining CNN, metadata, and handcrafted visual features.
- Validating advanced modeling feature tables.
- Building advanced regression models.
- Running fold-based cross-validation.
- Generating out-of-fold predictions.
- Calculating competition-style and standard regression metrics.
- Saving fitted fold models.
- Aggregating model comparison results.
- Selecting the best advanced model configuration.

The functions are designed to work with artifacts generated by:

- 02_data_preprocessing.ipynb
- 03_feature_extraction.ipynb
- 04_baseline_modeling.ipynb
- 05_visual_features_and_segmentation.ipynb

This module intentionally keeps experiment execution inside Notebook 06
while reusable modeling logic remains here.
"""

from __future__ import annotations

from pathlib import Path
from typing import Callable

import joblib
import numpy as np
import pandas as pd

from sklearn.base import RegressorMixin
from sklearn.ensemble import ExtraTreesRegressor, HistGradientBoostingRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
)

from src.config import RANDOM_SEED
from src.modeling import TARGET_COLUMNS


# ============================================================
# FEATURE CONFIGURATION
# ============================================================


IDENTIFIER_COLUMNS = {
    "image_path",
    "processed_image_path",
    "fold",
}


def identify_advanced_feature_columns(
    feature_table: pd.DataFrame,
) -> dict[str, list[str]]:
    """
    Identify CNN, metadata, visual, and fused feature configurations.

    Expected feature naming conventions:

    - CNN features begin with ``cnn_``.
    - Visual features begin with one of the known visual prefixes.
    - Remaining predictive columns are treated as metadata features.

    Parameters
    ----------
    feature_table : pandas.DataFrame
        Complete modeling feature table.

    Returns
    -------
    dict[str, list[str]]
        Mapping containing:

        - cnn
        - metadata
        - visual
        - cnn_metadata
        - cnn_visual
        - metadata_visual
        - all_features

    Raises
    ------
    ValueError
        If required feature groups cannot be identified.
    """

    visual_prefixes = (
        "rgb_",
        "hsv_",
        "exg_",
        "vegetation_",
        "brown_",
        "hist_",
        "texture_",
        "edge_",
    )

    cnn_columns = [
        column
        for column in feature_table.columns
        if column.startswith("cnn_")
    ]

    visual_columns = [
        column
        for column in feature_table.columns
        if column.startswith(visual_prefixes)
    ]

    excluded_columns = (
        IDENTIFIER_COLUMNS
        | set(TARGET_COLUMNS)
        | set(cnn_columns)
        | set(visual_columns)
    )

    metadata_columns = [
        column
        for column in feature_table.columns
        if column not in excluded_columns
    ]

    if len(cnn_columns) == 0:
        raise ValueError(
            "No CNN feature columns were identified."
        )

    if len(metadata_columns) == 0:
        raise ValueError(
            "No metadata feature columns were identified."
        )

    if len(visual_columns) == 0:
        raise ValueError(
            "No handcrafted visual feature columns were identified."
        )

    return {
        "cnn": cnn_columns,
        "metadata": metadata_columns,
        "visual": visual_columns,
        "cnn_metadata": cnn_columns + metadata_columns,
        "cnn_visual": cnn_columns + visual_columns,
        "metadata_visual": metadata_columns + visual_columns,
        "all_features": (
            cnn_columns
            + metadata_columns
            + visual_columns
        ),
    }


# ============================================================
# FEATURE TABLE VALIDATION
# ============================================================


def validate_advanced_feature_table(
    feature_table: pd.DataFrame,
    fold_column: str = "fold",
) -> dict:
    """
    Validate the advanced modeling feature table.

    Checks:

    - Input is a DataFrame.
    - Table is non-empty.
    - Fold column exists.
    - All target columns exist.
    - CNN features exist.
    - Metadata features exist.
    - Visual features exist.
    - Predictive features contain no NaN values.
    - Predictive features contain no infinite values.
    - Target values contain no NaN or infinite values.

    Parameters
    ----------
    feature_table : pandas.DataFrame
        Complete modeling feature table.

    fold_column : str, default="fold"
        Cross-validation fold column.

    Returns
    -------
    dict
        Validation statistics.
    """

    if not isinstance(feature_table, pd.DataFrame):
        raise TypeError(
            "feature_table must be a pandas DataFrame."
        )

    if len(feature_table) == 0:
        raise ValueError(
            "feature_table must contain at least one row."
        )

    if fold_column not in feature_table.columns:
        raise ValueError(
            f"Fold column '{fold_column}' is missing."
        )

    missing_targets = [
        target
        for target in TARGET_COLUMNS
        if target not in feature_table.columns
    ]

    if missing_targets:
        raise ValueError(
            f"Missing target columns: {missing_targets}"
        )

    feature_groups = identify_advanced_feature_columns(
        feature_table
    )

    predictive_columns = feature_groups["all_features"]

    predictive_values = feature_table[
        predictive_columns
    ].to_numpy(dtype=np.float32)

    target_values = feature_table[
        TARGET_COLUMNS
    ].to_numpy(dtype=np.float32)

    predictive_nan_count = int(
        np.isnan(predictive_values).sum()
    )

    predictive_inf_count = int(
        np.isinf(predictive_values).sum()
    )

    target_nan_count = int(
        np.isnan(target_values).sum()
    )

    target_inf_count = int(
        np.isinf(target_values).sum()
    )

    if predictive_nan_count > 0:
        raise ValueError(
            f"Predictive features contain "
            f"{predictive_nan_count} NaN values."
        )

    if predictive_inf_count > 0:
        raise ValueError(
            f"Predictive features contain "
            f"{predictive_inf_count} infinite values."
        )

    if target_nan_count > 0:
        raise ValueError(
            f"Targets contain {target_nan_count} NaN values."
        )

    if target_inf_count > 0:
        raise ValueError(
            f"Targets contain {target_inf_count} infinite values."
        )

    return {
        "n_samples": len(feature_table),
        "n_folds": feature_table[fold_column].nunique(),
        "n_cnn_features": len(feature_groups["cnn"]),
        "n_metadata_features": len(feature_groups["metadata"]),
        "n_visual_features": len(feature_groups["visual"]),
        "n_total_features": len(feature_groups["all_features"]),
        "n_targets": len(TARGET_COLUMNS),
        "predictive_nan_count": predictive_nan_count,
        "predictive_inf_count": predictive_inf_count,
        "target_nan_count": target_nan_count,
        "target_inf_count": target_inf_count,
    }


# ============================================================
# MODEL BUILDERS
# ============================================================


def build_extra_trees_model(
    n_estimators: int = 500,
    max_depth: int | None = None,
    min_samples_leaf: int = 1,
    max_features: str | float | int | None = 1.0,
    n_jobs: int = -1,
) -> ExtraTreesRegressor:
    """
    Build an Extra Trees multi-output regression model.
    """

    return ExtraTreesRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        random_state=RANDOM_SEED,
        n_jobs=n_jobs,
    )


def build_hist_gradient_boosting_model(
    learning_rate: float = 0.05,
    max_iter: int = 300,
    max_leaf_nodes: int = 31,
    l2_regularization: float = 1.0,
) -> HistGradientBoostingRegressor:
    """
    Build a HistGradientBoosting regression model.

    Note
    ----
    HistGradientBoostingRegressor does not natively support
    multi-output regression. It should therefore be wrapped using
    sklearn.multioutput.MultiOutputRegressor before training.
    """

    return HistGradientBoostingRegressor(
        learning_rate=learning_rate,
        max_iter=max_iter,
        max_leaf_nodes=max_leaf_nodes,
        l2_regularization=l2_regularization,
        random_state=RANDOM_SEED,
    )


def build_lightgbm_model(
    n_estimators: int = 500,
    learning_rate: float = 0.03,
    num_leaves: int = 31,
    max_depth: int = -1,
    subsample: float = 0.8,
    colsample_bytree: float = 0.8,
    n_jobs: int = -1,
):
    """
    Build a LightGBM regression model.

    LightGBM is imported lazily so the rest of the module remains
    usable even when LightGBM is not installed.
    """

    try:
        from lightgbm import LGBMRegressor

    except ImportError as exc:
        raise ImportError(
            "LightGBM is not installed. Install it using "
            "'pip install lightgbm'."
        ) from exc

    return LGBMRegressor(
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        num_leaves=num_leaves,
        max_depth=max_depth,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        random_state=RANDOM_SEED,
        n_jobs=n_jobs,
        verbosity=-1,
    )


def build_xgboost_model(
    n_estimators: int = 500,
    learning_rate: float = 0.03,
    max_depth: int = 6,
    subsample: float = 0.8,
    colsample_bytree: float = 0.8,
    n_jobs: int = -1,
):
    """
    Build an XGBoost regression model.

    XGBoost is imported lazily so the module remains usable when
    XGBoost is not installed.
    """

    try:
        from xgboost import XGBRegressor

    except ImportError as exc:
        raise ImportError(
            "XGBoost is not installed. Install it using "
            "'pip install xgboost'."
        ) from exc

    return XGBRegressor(
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        max_depth=max_depth,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        objective="reg:squarederror",
        random_state=RANDOM_SEED,
        n_jobs=n_jobs,
    )


def build_catboost_model(
    iterations: int = 500,
    learning_rate: float = 0.03,
    depth: int = 6,
):
    """
    Build a CatBoost regression model.

    CatBoost is imported lazily so the module remains usable when
    CatBoost is not installed.
    """

    try:
        from catboost import CatBoostRegressor

    except ImportError as exc:
        raise ImportError(
            "CatBoost is not installed. Install it using "
            "'pip install catboost'."
        ) from exc

    return CatBoostRegressor(
        iterations=iterations,
        learning_rate=learning_rate,
        depth=depth,
        loss_function="RMSE",
        random_seed=RANDOM_SEED,
        verbose=False,
    )


# ============================================================
# METRICS
# ============================================================


def calculate_advanced_regression_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    target_names: list[str] = TARGET_COLUMNS,
) -> pd.DataFrame:
    """
    Calculate MAE, RMSE, and R2 independently for every target.
    """

    if y_true.shape != y_pred.shape:
        raise ValueError(
            f"Shape mismatch: "
            f"y_true={y_true.shape}, "
            f"y_pred={y_pred.shape}."
        )

    records = []

    for target_index, target_name in enumerate(target_names):

        target_true = y_true[:, target_index]
        target_pred = y_pred[:, target_index]

        records.append(
            {
                "target": target_name,
                "MAE": mean_absolute_error(
                    target_true,
                    target_pred,
                ),
                "RMSE": np.sqrt(
                    mean_squared_error(
                        target_true,
                        target_pred,
                    )
                ),
                "R2": r2_score(
                    target_true,
                    target_pred,
                ),
            }
        )

    return pd.DataFrame(records)


# ============================================================
# ADVANCED CROSS-VALIDATION
# ============================================================


def run_advanced_cross_validation(
    feature_table: pd.DataFrame,
    feature_columns: list[str],
    model_builder: Callable,
    model_name: str,
    feature_set_name: str,
    fold_column: str = "fold",
    target_columns: list[str] = TARGET_COLUMNS,
    use_multioutput_wrapper: bool = False,
    clip_negative_predictions: bool = True,
    save_models: bool = False,
    model_output_dir: str | Path | None = None,
) -> tuple[np.ndarray, pd.DataFrame, dict]:
    """
    Run advanced fold-based cross-validation.

    For each fold:

    1. Select training and validation samples.
    2. Build a fresh regression model.
    3. Optionally wrap it using MultiOutputRegressor.
    4. Fit the model.
    5. Generate validation predictions.
    6. Optionally clip physically impossible negative predictions.
    7. Store aligned OOF predictions.
    8. Calculate per-target metrics.
    9. Optionally save fitted fold models.

    Returns
    -------
    tuple
        oof_predictions
        fold_metrics
        fitted_models
    """

    from sklearn.multioutput import MultiOutputRegressor

    missing_features = [
        column
        for column in feature_columns
        if column not in feature_table.columns
    ]

    if missing_features:
        raise ValueError(
            f"Missing feature columns: {missing_features[:10]}"
        )

    folds = sorted(
        feature_table[fold_column]
        .unique()
        .tolist()
    )

    y_all = feature_table[
        target_columns
    ].to_numpy(dtype=np.float32)

    oof_predictions = np.full(
        y_all.shape,
        np.nan,
        dtype=np.float32,
    )

    fold_metric_tables = []

    fitted_models = {}

    if save_models:

        if model_output_dir is None:
            raise ValueError(
                "model_output_dir must be provided "
                "when save_models=True."
            )

        model_output_dir = Path(model_output_dir)

        model_output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

    for fold in folds:

        train_mask = (
            feature_table[fold_column] != fold
        )

        validation_mask = (
            feature_table[fold_column] == fold
        )

        X_train = feature_table.loc[
            train_mask,
            feature_columns,
        ].to_numpy(dtype=np.float32)

        X_validation = feature_table.loc[
            validation_mask,
            feature_columns,
        ].to_numpy(dtype=np.float32)

        y_train = feature_table.loc[
            train_mask,
            target_columns,
        ].to_numpy(dtype=np.float32)

        y_validation = feature_table.loc[
            validation_mask,
            target_columns,
        ].to_numpy(dtype=np.float32)

        model = model_builder()

        if use_multioutput_wrapper:
            model = MultiOutputRegressor(model)

        model.fit(
            X_train,
            y_train,
        )

        validation_predictions = model.predict(
            X_validation
        )

        validation_predictions = np.asarray(
            validation_predictions,
            dtype=np.float32,
        )

        if clip_negative_predictions:
            validation_predictions = np.clip(
                validation_predictions,
                a_min=0.0,
                a_max=None,
            )

        validation_indices = np.flatnonzero(
            validation_mask.to_numpy()
        )

        oof_predictions[
            validation_indices
        ] = validation_predictions

        fold_metrics = calculate_advanced_regression_metrics(
            y_true=y_validation,
            y_pred=validation_predictions,
            target_names=target_columns,
        )

        fold_metrics.insert(
            0,
            "fold",
            fold,
        )

        fold_metrics.insert(
            0,
            "feature_set",
            feature_set_name,
        )

        fold_metrics.insert(
            0,
            "model",
            model_name,
        )

        fold_metric_tables.append(
            fold_metrics
        )

        fitted_models[fold] = model

        if save_models:

            model_path = (
                model_output_dir
                / f"{model_name}_{feature_set_name}_fold_{fold}.joblib"
            )

            joblib.dump(
                model,
                model_path,
            )

    if not np.isfinite(oof_predictions).all():
        raise ValueError(
            "OOF predictions contain NaN or infinite values."
        )

    all_fold_metrics = pd.concat(
        fold_metric_tables,
        ignore_index=True,
    )

    return (
        oof_predictions,
        all_fold_metrics,
        fitted_models,
    )


# ============================================================
# CROSS-VALIDATION SUMMARY
# ============================================================


def summarize_advanced_cv_results(
    fold_metrics: pd.DataFrame,
) -> pd.DataFrame:
    """
    Aggregate advanced CV metrics across folds.
    """

    summary = (
        fold_metrics
        .groupby(
            [
                "model",
                "feature_set",
                "target",
            ],
            as_index=False,
        )
        .agg(
            MAE_mean=("MAE", "mean"),
            MAE_std=("MAE", "std"),
            RMSE_mean=("RMSE", "mean"),
            RMSE_std=("RMSE", "std"),
            R2_mean=("R2", "mean"),
            R2_std=("R2", "std"),
        )
    )

    return summary


# ============================================================
# OVERALL MODEL RANKING
# ============================================================


def rank_model_configurations(
    cv_summary: pd.DataFrame,
) -> pd.DataFrame:
    """
    Rank model and feature-set configurations using average
    performance across all biomass targets.

    Lower RMSE and MAE are better.
    Higher R2 is better.
    """

    ranking = (
        cv_summary
        .groupby(
            [
                "model",
                "feature_set",
            ],
            as_index=False,
        )
        .agg(
            mean_MAE=("MAE_mean", "mean"),
            mean_RMSE=("RMSE_mean", "mean"),
            mean_R2=("R2_mean", "mean"),
        )
        .sort_values(
            by=[
                "mean_RMSE",
                "mean_MAE",
            ],
            ascending=[
                True,
                True,
            ],
        )
        .reset_index(drop=True)
    )

    ranking.insert(
        0,
        "rank",
        np.arange(
            1,
            len(ranking) + 1,
        ),
    )

    return ranking


# ============================================================
# OOF PREDICTION VALIDATION
# ============================================================


def validate_advanced_oof_predictions(
    predictions: np.ndarray,
    expected_samples: int,
    expected_targets: int = len(TARGET_COLUMNS),
) -> dict:
    """
    Validate advanced out-of-fold predictions.
    """

    expected_shape = (
        expected_samples,
        expected_targets,
    )

    if predictions.shape != expected_shape:
        raise ValueError(
            f"Expected prediction shape {expected_shape}, "
            f"received {predictions.shape}."
        )

    nan_count = int(
        np.isnan(predictions).sum()
    )

    inf_count = int(
        np.isinf(predictions).sum()
    )

    negative_count = int(
        np.sum(predictions < 0)
    )

    if nan_count > 0:
        raise ValueError(
            f"Predictions contain {nan_count} NaN values."
        )

    if inf_count > 0:
        raise ValueError(
            f"Predictions contain {inf_count} infinite values."
        )

    return {
        "n_samples": predictions.shape[0],
        "n_targets": predictions.shape[1],
        "dtype": str(predictions.dtype),
        "nan_count": nan_count,
        "inf_count": inf_count,
        "negative_prediction_count": negative_count,
        "prediction_min": float(np.min(predictions)),
        "prediction_max": float(np.max(predictions)),
        "prediction_mean": float(np.mean(predictions)),
        "prediction_std": float(np.std(predictions)),
    }


# ============================================================
# ARTIFACT SAVING
# ============================================================


def save_oof_predictions(
    feature_table: pd.DataFrame,
    predictions: np.ndarray,
    output_path: str | Path,
    model_name: str,
    feature_set_name: str,
) -> Path:
    """
    Save aligned OOF predictions to CSV.
    """

    output_path = Path(output_path)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    prediction_table = pd.DataFrame(
        predictions,
        columns=[
            f"pred_{target}"
            for target in TARGET_COLUMNS
        ],
    )

    if "image_path" in feature_table.columns:
        prediction_table.insert(
            0,
            "image_path",
            feature_table["image_path"].values,
        )

    if "fold" in feature_table.columns:
        prediction_table.insert(
            1,
            "fold",
            feature_table["fold"].values,
        )

    prediction_table["model"] = model_name
    prediction_table["feature_set"] = feature_set_name

    prediction_table.to_csv(
        output_path,
        index=False,
    )

    return output_path