"""
Baseline modeling utilities for the CSIRO Image2Biomass project.

This module provides reusable functionality for:

- Defining image, metadata, and combined feature configurations.
- Building baseline regression models.
- Running fold-based cross-validation.
- Generating out-of-fold predictions.
- Calculating regression metrics for multiple biomass targets.
- Aggregating cross-validation results.
- Validating model predictions and outputs.

The functions are designed to work with the fold assignments and
feature artifacts generated by 03_feature_extraction.ipynb.
"""

from typing import Callable

import numpy as np
import pandas as pd

from sklearn.base import RegressorMixin
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
)
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor

from src.config import (
    RANDOM_SEED,
    RIDGE_ALPHA,
    RF_N_ESTIMATORS,
    RF_MAX_DEPTH,
    RF_MIN_SAMPLES_LEAF,
    RF_N_JOBS,
)


# ============================================================
# TARGET CONFIGURATION
# ============================================================


TARGET_COLUMNS = [
    "Dry_Clover_g",
    "Dry_Dead_g",
    "Dry_Green_g",
    "Dry_Total_g",
    "GDM_g",
]


# ============================================================
# FEATURE COLUMN IDENTIFICATION
# ============================================================


def get_feature_columns(
    feature_table: pd.DataFrame,
) -> dict[str, list[str]]:
    """
    Identify CNN, metadata, and combined predictive feature columns.

    Parameters
    ----------
    feature_table : pandas.DataFrame
        Combined feature table generated by Notebook 03.

    Returns
    -------
    dict[str, list[str]]
        Dictionary containing CNN-only, metadata-only, and combined
        feature column lists.

    Raises
    ------
    ValueError
        If CNN or metadata feature columns cannot be identified.
    """

    cnn_columns = [
        column
        for column in feature_table.columns
        if column.startswith("cnn_")
    ]

    excluded_columns = {
        "image_path",
        "processed_image_path",
        "fold",
        *TARGET_COLUMNS,
    }

    metadata_columns = [
        column
        for column in feature_table.columns
        if column not in excluded_columns
        and not column.startswith("cnn_")
    ]

    if len(cnn_columns) == 0:
        raise ValueError(
            "No CNN feature columns were identified."
        )

    if len(metadata_columns) == 0:
        raise ValueError(
            "No metadata feature columns were identified."
        )

    combined_columns = (
        cnn_columns
        + metadata_columns
    )

    return {
        "cnn": cnn_columns,
        "metadata": metadata_columns,
        "combined": combined_columns,
    }


# ============================================================
# MODEL BUILDERS
# ============================================================


def build_ridge_model(
    alpha: float = RIDGE_ALPHA,
) -> RegressorMixin:
    """
    Build a multi-output Ridge regression baseline.

    Parameters
    ----------
    alpha : float, default=1.0
        L2 regularization strength.

    Returns
    -------
    sklearn.base.RegressorMixin
        Ridge regression model.
    """

    model = Ridge(
        alpha=alpha,
    )

    return model


def build_random_forest_model(
    n_estimators: int = RF_N_ESTIMATORS,
    max_depth: int | None = RF_MAX_DEPTH,
    min_samples_leaf: int = RF_MIN_SAMPLES_LEAF,
    n_jobs: int = RF_N_JOBS,
) -> RegressorMixin:
    """
    Build a multi-output Random Forest regression baseline.

    Parameters
    ----------
    n_estimators : int, default=300
        Number of trees.

    max_depth : int or None, default=None
        Maximum tree depth.

    min_samples_leaf : int, default=1
        Minimum number of samples required at a leaf node.

    n_jobs : int, default=-1
        Number of parallel CPU jobs.

    Returns
    -------
    sklearn.base.RegressorMixin
        Random Forest regression model.
    """

    model = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_leaf=min_samples_leaf,
        random_state=RANDOM_SEED,
        n_jobs=n_jobs,
    )

    return model


# ============================================================
# REGRESSION METRICS
# ============================================================


def calculate_regression_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    target_names: list[str] = TARGET_COLUMNS,
) -> pd.DataFrame:
    """
    Calculate regression metrics independently for each target.

    Metrics:

    - Mean Absolute Error (MAE)
    - Root Mean Squared Error (RMSE)
    - R-squared (R2)

    Parameters
    ----------
    y_true : numpy.ndarray
        Ground-truth target matrix.

    y_pred : numpy.ndarray
        Predicted target matrix.

    target_names : list[str], default=TARGET_COLUMNS
        Ordered target names.

    Returns
    -------
    pandas.DataFrame
        Per-target regression metrics.
    """

    if y_true.shape != y_pred.shape:
        raise ValueError(
            f"Shape mismatch: y_true={y_true.shape}, "
            f"y_pred={y_pred.shape}."
        )

    if y_true.ndim != 2:
        raise ValueError(
            "y_true and y_pred must be 2D arrays."
        )

    if y_true.shape[1] != len(target_names):
        raise ValueError(
            "Number of target columns does not match target names."
        )

    metric_records = []

    for target_index, target_name in enumerate(target_names):

        target_true = y_true[:, target_index]
        target_pred = y_pred[:, target_index]

        mae = mean_absolute_error(
            target_true,
            target_pred,
        )

        rmse = np.sqrt(
            mean_squared_error(
                target_true,
                target_pred,
            )
        )

        r2 = r2_score(
            target_true,
            target_pred,
        )

        metric_records.append(
            {
                "target": target_name,
                "MAE": mae,
                "RMSE": rmse,
                "R2": r2,
            }
        )

    metrics = pd.DataFrame(metric_records)

    return metrics


# ============================================================
# CROSS-VALIDATION
# ============================================================


def run_fold_cross_validation(
    feature_table: pd.DataFrame,
    feature_columns: list[str],
    model_builder: Callable[[], RegressorMixin],
    model_name: str,
    feature_set_name: str,
    fold_column: str = "fold",
    target_columns: list[str] = TARGET_COLUMNS,
) -> tuple[np.ndarray, pd.DataFrame]:
    """
    Run fold-based cross-validation and generate OOF predictions.

    For every fold:

    1. Use all other folds for model training.
    2. Train the requested regression model.
    3. Predict the held-out validation fold.
    4. Store predictions in original row positions.
    5. Calculate validation metrics independently for every target.

    Parameters
    ----------
    feature_table : pandas.DataFrame
        Combined feature table.

    feature_columns : list[str]
        Predictive feature columns.

    model_builder : Callable
        Function returning a new unfitted regression model.

    model_name : str
        Human-readable model name.

    feature_set_name : str
        Human-readable feature configuration name.

    fold_column : str, default="fold"
        Cross-validation fold column.

    target_columns : list[str], default=TARGET_COLUMNS
        Regression target columns.

    Returns
    -------
    tuple
        oof_predictions : numpy.ndarray
            OOF prediction matrix aligned with original table rows.

        fold_metrics : pandas.DataFrame
            Per-fold and per-target regression metrics.
    """

    if fold_column not in feature_table.columns:
        raise ValueError(
            f"Fold column '{fold_column}' is missing."
        )

    missing_features = [
        column
        for column in feature_columns
        if column not in feature_table.columns
    ]

    if missing_features:
        raise ValueError(
            f"Missing feature columns: {missing_features[:10]}"
        )

    missing_targets = [
        column
        for column in target_columns
        if column not in feature_table.columns
    ]

    if missing_targets:
        raise ValueError(
            f"Missing target columns: {missing_targets}"
        )

    folds = sorted(
        feature_table[fold_column]
        .unique()
        .tolist()
    )

    y_all = feature_table[
        target_columns
    ].to_numpy(dtype=np.float32)

    oof_predictions = np.full(
        y_all.shape,
        np.nan,
        dtype=np.float32,
    )

    fold_metric_tables = []

    for fold in folds:

        train_mask = (
            feature_table[fold_column] != fold
        )

        validation_mask = (
            feature_table[fold_column] == fold
        )

        X_train = feature_table.loc[
            train_mask,
            feature_columns,
        ].to_numpy(dtype=np.float32)

        X_validation = feature_table.loc[
            validation_mask,
            feature_columns,
        ].to_numpy(dtype=np.float32)

        y_train = feature_table.loc[
            train_mask,
            target_columns,
        ].to_numpy(dtype=np.float32)

        y_validation = feature_table.loc[
            validation_mask,
            target_columns,
        ].to_numpy(dtype=np.float32)

        model = model_builder()

        model.fit(
            X_train,
            y_train,
        )

        validation_predictions = model.predict(
            X_validation
        )

        validation_predictions = np.asarray(
            validation_predictions,
            dtype=np.float32,
        )

        validation_indices = np.flatnonzero(
            validation_mask.to_numpy()
        )

        oof_predictions[
            validation_indices
        ] = validation_predictions

        fold_metrics = calculate_regression_metrics(
            y_true=y_validation,
            y_pred=validation_predictions,
            target_names=target_columns,
        )

        fold_metrics.insert(
            0,
            "fold",
            fold,
        )

        fold_metrics.insert(
            0,
            "feature_set",
            feature_set_name,
        )

        fold_metrics.insert(
            0,
            "model",
            model_name,
        )

        fold_metric_tables.append(
            fold_metrics
        )

    if not np.isfinite(oof_predictions).all():
        raise ValueError(
            "OOF predictions contain NaN or infinite values."
        )

    all_fold_metrics = pd.concat(
        fold_metric_tables,
        ignore_index=True,
    )

    return (
        oof_predictions,
        all_fold_metrics,
    )


# ============================================================
# METRIC AGGREGATION
# ============================================================


def summarize_cv_metrics(
    fold_metrics: pd.DataFrame,
) -> pd.DataFrame:
    """
    Aggregate per-fold regression metrics.

    Parameters
    ----------
    fold_metrics : pandas.DataFrame
        Per-fold and per-target metrics generated during
        cross-validation.

    Returns
    -------
    pandas.DataFrame
        Mean and standard deviation of MAE, RMSE, and R2 for each
        model, feature set, and target.
    """

    required_columns = [
        "model",
        "feature_set",
        "target",
        "MAE",
        "RMSE",
        "R2",
    ]

    missing_columns = [
        column
        for column in required_columns
        if column not in fold_metrics.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Missing metric columns: {missing_columns}"
        )

    summary = (
        fold_metrics
        .groupby(
            [
                "model",
                "feature_set",
                "target",
            ],
            as_index=False,
        )
        .agg(
            MAE_mean=("MAE", "mean"),
            MAE_std=("MAE", "std"),
            RMSE_mean=("RMSE", "mean"),
            RMSE_std=("RMSE", "std"),
            R2_mean=("R2", "mean"),
            R2_std=("R2", "std"),
        )
    )

    return summary


# ============================================================
# PREDICTION VALIDATION
# ============================================================


def validate_oof_predictions(
    predictions: np.ndarray,
    expected_samples: int,
    expected_targets: int = len(TARGET_COLUMNS),
) -> dict:
    """
    Validate generated out-of-fold predictions.

    Parameters
    ----------
    predictions : numpy.ndarray
        OOF prediction matrix.

    expected_samples : int
        Expected number of rows.

    expected_targets : int, default=len(TARGET_COLUMNS)
        Expected number of target columns.

    Returns
    -------
    dict
        Prediction validation statistics.
    """

    expected_shape = (
        expected_samples,
        expected_targets,
    )

    if predictions.shape != expected_shape:
        raise ValueError(
            f"Expected prediction shape {expected_shape}, "
            f"received {predictions.shape}."
        )

    nan_count = int(
        np.isnan(predictions).sum()
    )

    inf_count = int(
        np.isinf(predictions).sum()
    )

    if nan_count > 0:
        raise ValueError(
            f"Predictions contain {nan_count} NaN values."
        )

    if inf_count > 0:
        raise ValueError(
            f"Predictions contain {inf_count} infinite values."
        )

    validation_results = {
        "n_samples": predictions.shape[0],
        "n_targets": predictions.shape[1],
        "dtype": str(predictions.dtype),
        "nan_count": nan_count,
        "inf_count": inf_count,
        "prediction_min": float(np.min(predictions)),
        "prediction_max": float(np.max(predictions)),
        "prediction_mean": float(np.mean(predictions)),
        "prediction_std": float(np.std(predictions)),
    }

    return validation_results